
"use client";

import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { PageHeader } from "@/components/page-header";
import { LayoutDashboard, ClipboardPlus, Users, PackageSearch, ReceiptText, TrendingUp, AlertTriangle } from "lucide-react";
import Link from "next/link";
import { Button } from "@/components/ui/button";
import { useEffect, useState, useCallback } from "react";
import { collection, getDocs, query, where, limit, orderBy, Timestamp, getCountFromServer } from 'firebase/firestore';
import { db, auth } from '@/lib/firebase/firebaseConfig';
import type { User as FirebaseUser } from "firebase/auth";
import { format, startOfWeek, endOfWeek, startOfDay, endOfDay } from 'date-fns'; // For formatting dates

/**
 * @fileOverview Store Manager Dashboard page.
 * Provides Store Managers with an overview of daily operations, key metrics relevant to them,
 * and quick actions. Data is fetched from Firebase Firestore, filtered for the current manager.
 */

/**
 * Interface for dashboard metric display.
 */
interface Metric {
  title: string;
  value: string;
  icon: React.ElementType;
  description?: string;
  dataAiHint?: string;
  link?: string; 
  isLoading: boolean;
}

/**
 * Interface for quick action button display.
 */
interface QuickAction {
  label: string;
  href: string;
  icon: React.ElementType;
  description: string;
}

// Quick actions for the Store Manager dashboard
const quickActions: QuickAction[] = [
    { label: "Create New Bill", href: "/create-bill", icon: ClipboardPlus, description: "Generate a new bill or invoice for a customer." },
    { label: "Manage Customers", href: "/customers?addNew=true", icon: Users, description: "View, add, or update customer information." },
    { label: "View Products & Stock", href: "/view-products-stock", icon: PackageSearch, description: "Check product prices, details, and current availability." },
];

/**
 * StoreManagerDashboardPage component.
 * Renders the main dashboard for Store Manager users, fetching and displaying
 * relevant metrics and activity from Firebase Firestore.
 * @returns {JSX.Element} The rendered store manager dashboard page.
 */
export default function StoreManagerDashboardPage() {
  const [recentActivity, setRecentActivity] = useState<string[]>([]);
  const [currentUser, setCurrentUser] = useState<FirebaseUser | null>(null);
  const [metrics, setMetrics] = useState<Metric[]>([
    { title: "Today's Bills Generated", value: "0", icon: ReceiptText, description: "Bills created by you today.", dataAiHint: "invoice document", isLoading: true, link: "/billing?filter=today&manager=me" },
    { title: "Customers Added This Week", value: "0", icon: Users, description: "New customers registered by you this week.", dataAiHint: "people team", isLoading: true, link: "/customers"},
    { title: "Pending Bills (Yours)", value: "0", icon: ReceiptText, description: "Your bills awaiting payment.", dataAiHint: "payment money", isLoading: true, link: "/billing?status=Pending&manager=me"},
    { title: "Reported Product Issues", value: "0", icon: AlertTriangle, description: "Issues you've reported (active).", dataAiHint: "alert inventory", isLoading: true, link: "/view-products-stock" }, 
  ]);

  // Get current authenticated user
  useEffect(() => {
    const unsubscribe = auth.onAuthStateChanged((user) => {
      setCurrentUser(user);
    });
    return () => unsubscribe();
  }, []);

  /**
   * Fetches dashboard data relevant to the current store manager from Firestore.
   */
  const fetchManagerDashboardData = useCallback(async () => {
    if (!currentUser) {
      console.log("StoreManagerDashboard: No current user, skipping data fetch.");
      // Set all metrics to not loading if user is null after initial check
      setMetrics(prevMetrics => prevMetrics.map(m => ({ ...m, isLoading: false, value: "N/A" })));
      return;
    }
    console.log("StoreManagerDashboard: Fetching data for user:", currentUser.uid);

    const today = new Date();
    // For "Today's Bills": Use ISO strings for date range queries if 'isoDate' is a string.
    // If 'isoDate' is a Firestore Timestamp, convert `todayStart` and `todayEnd` to Timestamps.
    const todayStartISO = startOfDay(today).toISOString();
    const todayEndISO = endOfDay(today).toISOString();
    
    // For "Customers Added This Week": Use Firestore Timestamps for range queries on 'createdAt'.
    const weekStart = startOfWeek(today, { weekStartsOn: 1 }); // Assuming week starts on Monday
    const weekEnd = endOfWeek(today, { weekStartsOn: 1 });
    const weekStartTimestamp = Timestamp.fromDate(weekStart);
    const weekEndTimestamp = Timestamp.fromDate(weekEnd);


    const updateMetric = (title: string, newValue: Partial<Metric>) => {
      setMetrics(prevMetrics => 
        prevMetrics.map(m => m.title === title ? { ...m, ...newValue, isLoading: false } : m)
      );
    };

    try {
      // 1. Today's Bills Generated by this manager
      // Assumes 'invoices' collection has 'createdBy' (UID) and 'isoDate' (ISO string YYYY-MM-DDTHH:mm:ss.sssZ)
      const todaysBillsQuery = query(
        collection(db, "invoices"), 
        where("createdBy", "==", currentUser.uid),
        where("isoDate", ">=", todayStartISO),
        where("isoDate", "<=", todayEndISO)
      );
      const todaysBillsSnapshot = await getCountFromServer(todaysBillsQuery);
      updateMetric("Today's Bills Generated", { value: todaysBillsSnapshot.data().count.toString() });

      // 2. Customers Added This Week by this manager
      // Assumes 'customers' collection has 'createdBy' (UID) and 'createdAt' (Firestore Timestamp)
      const customersAddedQuery = query(
        collection(db, "customers"),
        where("createdBy", "==", currentUser.uid), 
        where("createdAt", ">=", weekStartTimestamp),
        where("createdAt", "<=", weekEndTimestamp)
      );
      const customersAddedSnapshot = await getCountFromServer(customersAddedQuery);
      updateMetric("Customers Added This Week", { value: customersAddedSnapshot.data().count.toString() });

      // 3. Pending Bills created by this manager
      // Assumes 'invoices' collection has 'createdBy' (UID) and 'status'
      const pendingBillsQuery = query(
          collection(db, "invoices"),
          where("createdBy", "==", currentUser.uid),
          where("status", "==", "Pending")
      );
      const pendingBillsSnapshot = await getCountFromServer(pendingBillsQuery);
      updateMetric("Pending Bills (Yours)", {value: pendingBillsSnapshot.data().count.toString()});

      // 4. Reported Product Issues by this manager (active issues)
      // Assumes 'issueReports' collection has 'reportedByUid' (UID) and 'status'
      const reportedIssuesQuery = query(
          collection(db, "issueReports"),
          where("reportedByUid", "==", currentUser.uid),
          where("status", "==", "New") // Only count 'New' or 'Investigating' issues
      );
      const reportedIssuesSnapshot = await getCountFromServer(reportedIssuesQuery);
      updateMetric("Reported Product Issues", {value: reportedIssuesSnapshot.data().count.toString()});


      // Fetch recent activity (e.g., last 3 bills created by this manager)
      // Assumes 'invoices' collection has 'createdBy' (UID) and 'createdAt' (Firestore Timestamp)
      const recentActivityQuery = query(
        collection(db, "invoices"), 
        where("createdBy", "==", currentUser.uid), 
        orderBy("createdAt", "desc"), 
        limit(3)
      );
      const activitySnapshot = await getDocs(recentActivityQuery);
      const activities = activitySnapshot.docs.map(doc => {
        const data = doc.data();
        // Ensure createdAt is a Timestamp before calling toDate()
        const dateFormatted = data.createdAt instanceof Timestamp 
            ? format(data.createdAt.toDate(), "MMM dd, HH:mm") 
            : (data.isoDate ? format(new Date(data.isoDate), "MMM dd, HH:mm") : "Recently");
        return `${dateFormatted}: Bill ${data.invoiceNumber || 'N/A'} created for ${data.customerName || 'Unknown'}.`;
      });
      setRecentActivity(activities);

    } catch (error) {
      console.error("Error fetching store manager dashboard data:", error);
      // Set all metrics to error state or display a general error toast
      metrics.forEach(m => updateMetric(m.title, { value: "Error", isLoading: false }));
      setRecentActivity(["Failed to load recent activity due to an error."]);
    }
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [currentUser]); // metrics removed from deps to avoid loop

  useEffect(() => {
    if (currentUser) {
      fetchManagerDashboardData();
    }
  }, [currentUser, fetchManagerDashboardData]);

  return (
    <>
      <PageHeader
        title="Store Manager Dashboard"
        description="Your daily operations hub for sales, customers, and inventory management."
        icon={LayoutDashboard}
      />
      <div className="grid gap-6 md:grid-cols-2 lg:grid-cols-4">
        {metrics.map((metric) => (
          <Card key={metric.title} className="shadow-lg rounded-xl hover:shadow-primary/20 transition-shadow">
            <Link href={metric.link || "#"} className={metric.link ? "" : "pointer-events-none"}>
              <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
                <CardTitle className="text-sm font-medium text-muted-foreground">
                  {metric.title}
                </CardTitle>
                <metric.icon className="h-5 w-5 text-primary" data-ai-hint={metric.dataAiHint} />
              </CardHeader>
              <CardContent>
                {metric.isLoading ? (
                  <div className="text-2xl font-bold font-headline text-foreground animate-pulse">Loading...</div>
                ) : (
                  <div className="text-2xl font-bold font-headline text-foreground">{metric.value}</div>
                )}
                {metric.description && !metric.isLoading && (
                    <p className="text-xs text-muted-foreground pt-1">{metric.description}</p>
                )}
              </CardContent>
            </Link>
          </Card>
        ))}
      </div>
      
      <div className="mt-8">
        <Card className="shadow-lg rounded-xl">
          <CardHeader>
            <CardTitle className="font-headline text-foreground">Quick Actions</CardTitle>
             <CardDescription>Quickly access common tasks relevant to your role.</CardDescription>
          </CardHeader>
          <CardContent className="grid gap-4 sm:grid-cols-1 md:grid-cols-2 lg:grid-cols-3">
            {quickActions.map((action) => (
                <Link href={action.href} key={action.label} passHref legacyBehavior>
                    <Button variant="outline" className="w-full h-auto justify-start p-4 text-left flex items-start gap-3 hover:bg-accent/10 transition-colors group">
                        <action.icon className="h-7 w-7 text-primary mt-1 transition-transform group-hover:scale-110" />
                        <div className="flex-1">
                            <span className="text-base font-medium text-foreground">{action.label}</span>
                            <p className="text-xs text-muted-foreground">{action.description}</p>
                        </div>
                    </Button>
                </Link>
            ))}
          </CardContent>
        </Card>
      </div>

       <div className="mt-8">
        <Card className="shadow-lg rounded-xl">
          <CardHeader>
            <CardTitle className="font-headline text-foreground flex items-center"><TrendingUp className="mr-2 h-6 w-6 text-primary" />Your Recent Activity</CardTitle>
             <CardDescription>Latest interactions and tasks performed by you.</CardDescription>
          </CardHeader>
          <CardContent>
             {recentActivity.length > 0 ? (
                <ul className="space-y-2">
                    {recentActivity.map((activity, index) => (
                        <li key={index} className="text-sm text-muted-foreground p-3 border-b last:border-b-0 hover:bg-muted/30 rounded-md transition-colors">
                            {activity}
                        </li>
                    ))}
                </ul>
             ) : ( 
                <div className="h-48 flex items-center justify-center bg-muted/30 rounded-md border border-dashed">
                    <p className="text-muted-foreground">{!currentUser && metrics.some(m=>m.isLoading) ? "Loading user data..." : "No recent activity to display."}</p>
                </div>
             )}
          </CardContent>
        </Card>
      </div>
    </>
  );
}

